# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Install V (via the community setup action)
      - name: Set up V
        uses: vlang/setup-v@v1.4
        with:
          version: 'latest'

      # 3. Run your Makefile targets
      - name: Run checks and build
        run: make build
